### ISSUE TITLE
Aprimoramentos

### ISSUE THREAD

**Issue by eduardojsilvajr** [1cgeo/ferramentas_pto_controle#5]
estudando a metodologia proposta notei que o padrão de pontos usado nas explicações do GIT e dos relatórios técnicos usam o padrão UF-HV-001 mas na pelo código dentro da evaluateStructure.py o correto seria UF-HV1
`def evaluate_nome_ponto(nome):
        pto_regex = "^[A-Z][A-Z]-(HV|Base)-[1-9]+[0-9]*$"
        if search(pto_regex, nome):
            return True
        else:
            return False`

outros possíveis aprimoramentos seriam:

- uma descrição sucinta do que são cada um dos atributos do banco de dados(alguns atributos são lógicos, mas alguns não o são, "altitude_objeto"

- um csv de modelo de metadado disponível pra download, existem padrões de preenchimento que devem ser seguidos e não estão claros (hora no formato HH:MM). os tempos de inicio e fim de rastreio devem ser preenchidos em horário local e não GMT.

`def parse_date(text):
        for fmt in ('%H:%M', '%H:%M:00'):`

**Comment by dinizime** [comment]
Obrigado @eduardojsilvajr.

Quanto ao padrão na metodologia está errado mesmo. o correto é UF-HV-1.

O @elitonfilho irá atualizar o readme para refletir essas observações.

**Comment by elitonfilho** [comment]
O readme foi atualizado em d6166d1 para deixar o preenchimento dos atributos mais transparente
