### ISSUE TITLE
atualização na rotina 4-prepara PPP

### ISSUE THREAD

**Issue by eduardojsilvajr** [1cgeo/ferramentas_pto_controle#6]
A função zipaPPP no código handlebeforePPP.py está travada para pontos coletados no ano de 2018

`def zipaPPP(pasta):
    for root, dirs, files in os.walk(pasta):
        if Path(root).parts[-1] == "2_RINEX":
            pto = Path(root).parts[-2]
            if (pto + ".18n") in files and (pto + ".18o") in files and not (pto + ".zip") in files:
                zf = zipfile.ZipFile(os.path.join(
                    root, pto + ".zip"), "w", zipfile.ZIP_DEFLATED)
                zf.write(os.path.join(root, pto + ".18n"), pto + ".18n")
                zf.write(os.path.join(root, pto + ".18o"), pto + ".18o")`

**Comment by elitonfilho** [comment]
Obrigado pelo feedback @eduardojsilvajr !
O commit f33f624 resolve o problema da rotina aceitar apenas o ano de 2018. Se a rotina ainda estiver com problemas é só mandar uma mensagem neste issue
